apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/namespace.yaml
  - base/serviceaccount.yaml
  - observability/namespace.yaml
  - observability/rbac.yaml
  - observability/prometheus-configmap.yaml
  - observability/prometheus-rules.yaml
  - observability/loki-config.yaml
  - observability/grafana-datasources.yaml
  - observability/grafana-dashboards.yaml
  - observability/alertmanager-config.yaml
  - observability/servicemonitor.yaml
  - users-service/deployment.yaml
  - users-service/service.yaml
  - gateway/deployment.yaml
  - gateway/service.yaml
  - gateway/ingress.yaml
  - analytics-service/deployment.yaml
  - analytics-service/service.yaml
  - notification-service/deployment.yaml
  - notification-service/service.yaml
  - plagiarism-service/deployment.yaml
  - plagiarism-service/service.yaml
  - submission-service/deployment.yaml
  - submission-service/service.yaml
configurations:
  - kustomizeconfig.yaml
# GitHub workflows will update this images section with new digests
images:
  - name: h20240192/ss_g527.paper-submission-portal
    newName: h20240192/ss_g527.paper-submission-portal
    digest: sha256:b6e8972b2dec192264481343d91034cc8f023bcb39f460aa28108e5d8af31056
argo_update: "2025-11-26T16:41:01Z"
