apiVersion: apps/v1
kind: Deployment
metadata:
  name: plagiarism-service
  namespace: paper-submission-portal
  labels:
    app: plagiarism-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plagiarism-service
  template:
    metadata:
      labels:
        app: plagiarism-service
    spec:
      containers:
        - name: plagiarism-service
          image: h20240192/ss_g527.paper-submission-portal@sha256:3a5fe6d7517ffd179ecc6c4905de57ff78325e32e13e401752cc12446f3035f0
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
          env:
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: LOG_LEVEL
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
