apiVersion: apps/v1
kind: Deployment
metadata:
  name: plagiarism-service
  namespace: paper-submission-portal
  labels:
    app: plagiarism-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: plagiarism-service
  template:
    metadata:
      labels:
        app: plagiarism-service
    spec:
      containers:
      - name: plagiarism-service
        image: paper-submission-portal/plagiarism_service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8004
        env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOG_LEVEL
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
