apiVersion: apps/v1
kind: Deployment
metadata:
  name: plagiarism-service
  namespace: paper-submission-portal
  labels:
    app: plagiarism-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plagiarism-service
  template:
    metadata:
      labels:
        app: plagiarism-service
    spec:
      containers:
        - name: plagiarism-service
          image: h20240192/ss_g527.paper-submission-portal@sha256:8d20b050e85975a43df5d33d05fe70f3dffbcd139397579d8f912ddcca7e659c
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
          env:
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: LOG_LEVEL
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
