apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudsql-sa
  namespace: paper-submission-portal
  labels:
    app: cloudsql-proxy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: paper-submission-portal
  labels:
    app: default
